package org.vinni.cliente.gui;

import javax.swing.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;

/**
 * author: Vinni 2024
 */
public class PrincipalCli extends javax.swing.JFrame {

    private final int PORT = 12345;
    // Debe coincidir con PrincipalSrv.PREFIJO_ID_CLIENTE: es el prefijo que
    // usa el servidor para avisarle a este cliente cuál es su propio número.
    private static final String PREFIJO_ID_CLIENTE = "ID_ASIGNADO:";
    // Deben coincidir con PrincipalSrv.DESTINO_TODOS / SEPARADOR_DESTINO: el
    // mini-protocolo con el que este cliente le dice al servidor a quién va
    // dirigido cada mensaje: "<destino>|<mensaje>".
    private static final String DESTINO_TODOS = "TODOS";
    private static final String SEPARADOR_DESTINO = "|";
    private Socket socket;
    private PrintWriter out;
    private BufferedReader in;
    private String idCliente = "?";

    /**
     * Creates new form Principal1
     */
    public PrincipalCli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        this.setTitle("Cliente ");
        bConectar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajesTxt = new javax.swing.JTextArea();
        mensajeTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btEnviar = new javax.swing.JButton();
        jLabelDestino = new javax.swing.JLabel();
        destinoTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bConectar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bConectar.setText("CONECTAR CON SERVIDOR");
        bConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectarActionPerformed(evt);
            }
        });
        getContentPane().add(bConectar);
        bConectar.setBounds(260, 40, 210, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("CLIENTE TCP : DFRACK");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 250, 17);

        mensajesTxt.setColumns(20);
        mensajesTxt.setRows(5);
        mensajesTxt.setEnabled(false);
        jScrollPane1.setViewportView(mensajesTxt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 240, 410, 110);

        jLabelDestino.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDestino.setText("Destino (ID o vacío = TODOS):");
        getContentPane().add(jLabelDestino);
        jLabelDestino.setBounds(20, 88, 220, 20);

        destinoTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(destinoTxt);
        destinoTxt.setBounds(250, 85, 90, 25);

        mensajeTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(mensajeTxt);
        mensajeTxt.setBounds(40, 150, 350, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Mensaje:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 120, 120, 30);

        btEnviar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btEnviar);
        btEnviar.setBounds(327, 190, 120, 27);

        setSize(new java.awt.Dimension(491, 405));
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void bConectarActionPerformed(java.awt.event.ActionEvent evt) {
        conectar();
    }
    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {
        this.enviarMensaje();

    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalCli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton bConectar;
    private javax.swing.JButton btEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mensajesTxt;
    private JTextField mensajeTxt;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JTextField destinoTxt;
    // End of variables declaration

    private void conectar() {
        JOptionPane.showMessageDialog(this, "Conectando con servidor");
        try {
            if (socket == null || socket.isClosed()) {
                socket = new Socket("localhost", PORT); // Asume que el servidor está en localhost y escucha en el puerto 5555
                out = new PrintWriter(socket.getOutputStream(), true);
            }
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            new Thread(new Runnable() {
                public void run() {
                    try {
                        String fromServer;
                        while ((fromServer = in.readLine()) != null) {
                            if (fromServer.startsWith(PREFIJO_ID_CLIENTE)) {
                                idCliente = fromServer.substring(PREFIJO_ID_CLIENTE.length());
                                SwingUtilities.invokeLater(new Runnable() {
                                    public void run() {
                                        setTitle("Cliente " + idCliente + " - Cliente TCP: DFRACK");
                                        jLabel1.setText("CLIENTE TCP : DFRACK (Cliente " + idCliente + ")");
                                        mensajesTxt.append("Eres el Cliente " + idCliente + "\n");
                                    }
                                });
                            } else {
                                final String mensaje = fromServer;
                                SwingUtilities.invokeLater(new Runnable() {
                                    public void run() {
                                        mensajesTxt.append("Servidor: " + mensaje + "\n");
                                    }
                                });
                            }
                        }
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
            }).start();
            System.out.println(out);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar con el servidor: " + e.getMessage());
        }
    }
    private void enviarMensaje() {
        String mensaje = mensajeTxt.getText();
        if (mensaje.isEmpty()) {
            return;
        }
        String destino = destinoTxt.getText().trim();
        if (destino.isEmpty()) {
            destino = DESTINO_TODOS;
        }

        // Formato enviado al servidor: "<destino>|<mensaje>". El servidor
        // decide si difundirlo a todos o entregarlo solo a un cliente según
        // este mismo mini-protocolo (ver PrincipalSrv.ClienteHandler.procesarLinea).
        out.println(destino + SEPARADOR_DESTINO + mensaje);

        // Eco local inmediato: cada cliente muestra su propio mensaje enviado
        // (quién lo envía -este mismo cliente-, a quién, y el texto), sin
        // esperar a que el servidor se lo reenvíe de vuelta.
        String etiquetaDestino = DESTINO_TODOS.equals(destino) ? "TODOS" : ("Cliente " + destino);
        mensajesTxt.append("Yo (Cliente " + idCliente + ") -> " + etiquetaDestino + ": " + mensaje + "\n");

        mensajeTxt.setText("");
    }
}
